[package]
name = "game"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.n64]
path = "../n64"

[target.mips-nintendo64-none.dependencies]
rrt0 = "0.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"