[package]
name = "n64"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
n64-math = { path = "../n64-math" }

[target.'cfg(not(target_vendor = "nintendo64"))'.dependencies]
minifb = "0.14"
rayon = "1"

[target.'cfg(target_vendor = "nintendo64")'.dependencies]
n64-sys = { path = "../n64-sys" }
